w = read.table("household_power_consumption.txt",sep= ";", header=T,stringsAsFactors = FALSE)
t = subset(w, w$Date == "1/2/2007"|w$Date == "2/2/2007",stringsAsFactors = FALSE)
with (t, plot(Sub_metering_1, type="l",ylab = "Energy Sub Metering"))
par(new=T)
with (t, plot(Sub_metering_2, type="l",col="blue", ylab = NA, xlab= NA,axes = FALSE))
par(new=T)
with (t, plot(Sub_metering_2, type="l",col="red",ylab = NA, xlab= NA,axes = FALSE))
legend("topright", pch = 20, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
par(new=F)
dev.copy(png, file = "plot3.png") 
dev.off() 