w = read.table("household_power_consumption.txt",sep= ";", header=T,stringsAsFactors = FALSE)
t = subset(w, w$Date == "1/2/2007"|w$Date == "2/2/2007",stringsAsFactors = FALSE)
par(mfrow = c(2, 2))
with (t, {plot(Global_active_power, type = "l", axes= FALSE,ylab = "Global Active Power(kilowatts)") 
          axis(side=1, at=c(0,1500,2900),labels=c("Tru","Fri","Sat")) 
          axis(2)
          plot(Voltage,type = "l", ylab = "Voltage",axes= FALSE)
          axis(side=1, at=c(0,1500,2900),labels=c("Tru","Fri","Sat")) 
          axis(2)
          with (t, plot(Sub_metering_1, type="l",axes = FALSE,ylab = "Energy Sub Metering"))
          par(new=T)
          with (t, plot(Sub_metering_2, type="l",col="blue", ylab = NA, xlab= NA,axes = FALSE))
          par(new=T)
          with (t, plot(Sub_metering_2, type="l",col="red",ylab = NA, xlab= NA,axes = FALSE))
          legend("topright", pch = 20, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
          axis(side=1, at=c(0,1500,2900),labels=c("Tru","Fri","Sat")) 
          axis(2)
          par(new=F)
          plot(Global_reactive_power,type = "l", ylab = "Global_reactive_power")
          axis(side=1, at=c(0,1500,2900),labels=c("Tru","Fri","Sat")) 
          axis(2)})
dev.copy(png, file = "plot4.png") 
dev.off() 